### ISSUE TITLE
IPA Manager Update Fails on macOS

### ISSUE THREAD

**Issue by jvradelis** [K8TIY/IPAPalette#2]
When I attempt to update IPA Manager/Palette from the IPA Manager app on macOS 10.12.3, the update fails with this error:

    "An error occurred while extracting the archive."

Is there an alternative way to acquire the update?  The .dmg that is downloaded installs 2.2, not 2.2.1.

**Comment by K8TIY** [comment]
The current source archive should be able to do auto-updates with Sparkle 1.22, but unfortunately existing copies of IPA Manager (2.2.X versions) can't install updates. That's actually okay because there have not been any updates for about five years, but one is coming soon.

**Comment by K8TIY** [comment]
Versions 2.3 and 2.3.1 have integrated a release version of Sparkle different and more stable than previous versions, so I am counting this as done.
