### ISSUE TITLE
Scripting support (was: Shortcuts)

### ISSUE THREAD

**Issue by schmidhauser** [K8TIY/IPAPalette#6]
Thanks very much for the IPA Palette! It’s very useful. It would be great if the user could assign it a shortcut. I’d use it even more then. One of the reasons I’m unable to do so seems to be that the Palette – in contrast to macOS’s Keyboard Viewer, for instance – is not running as an application, which means it cannot be captured by Keyboard Maestro. Or did I miss something? 

I attach a screenshot of my KM configuration to illustrate what I was trying to do with the IPA Palette:

<img width="497" alt="Keyboard_Maestro" src="https://user-images.githubusercontent.com/519178/73139513-9b320100-4023-11ea-9ef0-16f1149f1f54.png">

**Comment by K8TIY** [comment]
This is a good suggestion.

IPA Palette is pretty much a full-fledged app, but the fact that it is set as an LSUIElement in the property list means it doesn't get a menu bar or related events, doesn't show up in Dock, and a plethora of other things. Now, exactly what makes it different from Keyboard Viewer for the purposes of KM I do not know. I haven't crawled inside Keyboard Viewer to look around in quite some time, but apparently it has gotten quite the overhaul for Catalina (https://bitsplitting.org/2019/10/05/catalinas-custom-keyboard-viewers/). I will look into the issues of getting keyboard shortcuts for input methods. I know it has been tried and maybe done, but I don't recall the technical specifics.

**Comment by K8TIY** [comment]
I downloaded the KM demo and -- I think -- managed to get a shortcut that activates the Palette. In creating the macro, since KM hides your ~/Library folder, I had to use Finder Go to Folder… menu item and type in ~/Library/Input Methods, then drag IPAPalette.app into KM. It created an "Activate IPAPalette" action. I didn't try the "deactivate" part of the logic. Anyway, the activate part of the keyboard shortcut seemed to work for me. (That seemed too easy.)

**Comment by K8TIY** [comment]
I did activate and deactivate. The Flag Menu doesn't seem to realize that IPA Palette is really active when KM activates it, so you could probably get into some weird states. But I did seem to get an acceptable first try at a shortcut.
<img width="490" alt="Screen Shot 2020-01-26 at 3 57 07 PM" src="https://user-images.githubusercontent.com/487483/73141687-ced94f00-4054-11ea-8e25-6f7006149d21.png">

**Comment by schmidhauser** [comment]
Many thanks for the comments. Unfortunately it doesn’t quite work for me. My main problem is that I cannot *start* IPA Palette as an application. For example, only the former of the following two commands has the expected outcome:
```
open -a keyboardviewer
open -a ipapalette
```
In other words, I have no difficulty hiding the Palette when it is running by means of a shortcut; but it does not seem possible to reactivate or restart it in the same way.

**Comment by K8TIY** [comment]
True enough. Generally the proper way to fire up IPA Palette, or another input method, is to use the C API TISSelectInputSource(), which is presumably what the flag menu is doing. I assume Keyboard Maestro can invoke an AppleScript as an action, so what I really should do is make IPA Manager scriptable, and allow it to respond to something like "tell application IPA Manager to select palette" and "tell application IPA Manager to deselect palette" (forgive my awful AppleScript, it's not a language I ever use.)

IPA Manager doesn't do very much, but it does know how to talk to Text Input Sources APIs. I've never done a scriptable app, but I read some examples and this modest functionality should not be difficult.

**Comment by schmidhauser** [comment]
That sounds great. I’m looking forward to it.

**Comment by K8TIY** [comment]
I have a prerelease version of scriptable IPA Manager at https://blugs.com/Downloads/IPAPalette_2.3.3_pre.dmg and am anxious for you to take a look at it.

It exports the commands show_palette and hide_palette, so I think all you need to do (after installation) is have a script say "tell application 'IPA Manager' show_palette end tell"

<img width="364" alt="Screen Shot 2020-01-31 at 11 12 15 AM" src="https://user-images.githubusercontent.com/487483/73554942-ac5f8100-441a-11ea-8090-5cfc9caf4364.png">

**Comment by schmidhauser** [comment]
It works. In case someone else is looking to do the same, here’s my KM configuration:

![ipa-show](https://user-images.githubusercontent.com/519178/73614087-dea2e700-45b0-11ea-9cd5-8243047c4e43.png)

![ipa-hide](https://user-images.githubusercontent.com/519178/73614101-ef535d00-45b0-11ea-8a88-1189d3358430.png)

To show the Palette, one can now use the little AppleScript you mentioned. To hide it again, however, it seems that one still has to quit the IPA Manager – at any rate, I haven’t been able to come up with something better.

When I run the script to show the Palette, I cannot directly click on the symbol I’d like to insert into my document. First, I have to click again on my text editor and only then can I click on the symbol I’d like to insert. It would be nice if this extra-step could be eliminated, too. But it’s a small detail, of course.

Two further suggestions: 

- The IPA Manager Help submenu says “Help isn’t available for IPA Manager”. Perhaps you could link instead to https://www.blugs.com/IPAPalette/doc.html.
- Perhaps you could also add an icon to `IPAPalette.app`.

Thank you.

**Comment by K8TIY** [comment]
I find it bizarre that IPA Manager must be quit in order to hide/quit the palette. I can't account for that. But, fortunately, there's no reason for IPA Manager to be left open, it is just an installer/update checker. (And if there were an alternative to it I would get rid of it in a heartbeat. Installers are horrible, Windows-ey things.)

The issue with the target document needing to be activated is unavoidable due to the fact that IPA Palette is a background-only (background-mostly?) app and the active app has to be the one with the document being edited. I don't think there's anything to be done about that.

Your two final suggestions have been spun off into separate issues, as they are both valid. See #8 and #9

**Comment by K8TIY** [comment]
Closing issue, as scripting support will be included in 2.3.3 release.
